name: Playwright Automation CI

on:
  workflow_dispatch:
    # inputs:
    #   test-type:
    #     description: Choose testing type
    #     required: false
    #     default: 'saucelabs'
    #     type: choice
    #     options:
    #       - local
    #       - saucelabs
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  test:
    name: UI & API Automation
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]

    env:
      ENV: qa
      BASE_URL: https://automationexercise.com/
      API_BASE_URL: https://reqres.in
      HEADLESS: true
      BROWSER: chromium

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: playwright-e2e
        run: npm ci

      - name: Install Playwright browsers
        working-directory: playwright-e2e
        run: npx playwright install --with-deps

      - name: Run tests (sharded)
        working-directory: playwright-e2e
        env:
          ENVIRONMENT: INTEROP
          TZ: Australia/Adelaide
        run: |
          npm run test:interop
        continue-on-error: true

      # - name: Run tests (sharded)
      #   run: |
      #     npx playwright test --shard=${{ matrix.shard }}/2

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shard }}
          path: |
            playwright-e2e/playwright-report
            playwright-e2e/reports
            playwright-e2e/logs

      - name: Checkout gh-pages Branch  
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: playwright-e2e/reports/allure-results
          gh_pages: gh-pages
          allure_report: playwright-e2e/reports/allure-report
          allure_history: playwright-e2e/reports/allure-history
          keep_reports: 7
          subfolder: AutomationReports/UI

      # - name: Deploy report to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: playwright-e2e/reports/allure-history
      #     keep_files: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: playwright-e2e/reports/allure-history
          keep_files: true
