name: Playwright Automation CI

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # JOB 1: Run Tests inside Docker
  test:
    name: UI & API Automation (Docker)
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy

    env:
      ENV: qa
      BASE_URL: https://automationexercise.com/
      API_BASE_URL: https://reqres.in
      HEADLESS: true
      BROWSER: chromium

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: playwright-e2e
        run: |
          npm ci

      - name: Run tests
        working-directory: playwright-e2e
        env:
          ENVIRONMENT: INTEROP
          TZ: Australia/Adelaide
        run: |
          npm run test:interop
        continue-on-error: true

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: playwright-e2e/reports/allure-results

  # JOB 2: Merge and Deploy
  deploy-report:
    name: Deploy Allure Report
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 7
          subfolder: AutomationReports/UI

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true

      - name: Print Report URL
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          echo "âœ… Report published successfully!"
          echo "ðŸ“Š Report URL: https://${OWNER}.github.io/${REPO_NAME}/AutomationReports/UI/${{ github.run_number }}"
